rpms:
  - distrobox
  - gnome-tweaks
  - just
  - vanilla-first-setup
  # Needed for vanilla-first-setup
  - vte
flatpaks:
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gnome.DejaDup
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
